function [error, message] = checkEventOverlapWithManualSleepWindow(app, thisEvents)

% Assume all is right
error = false;
message = {''};

manualEvents = selectEventsUsingTime(app.ACT.analysis.events, app.ACT.xmin, app.ACT.xmax, ...
    'Label', 'sleepWindow', ...
    'Type', 'manual', ...
    'Enclosed', false);

for ei = 1:size(manualEvents, 1)
    overlap = ...
        (...
        thisEvents.onset >= manualEvents.onset(ei) & ...
        thisEvents.onset <= manualEvents.onset(ei) + manualEvents.duration(ei) ...
        ) | (...
        thisEvents.onset+thisEvents.duration >= manualEvents.onset(ei) & ...
        thisEvents.onset+thisEvents.duration <= manualEvents.onset(ei) + manualEvents.duration(ei) ...
        ) | (...
        thisEvents.onset <= manualEvents.onset(ei) & ...
        thisEvents.onset+thisEvents.duration >= manualEvents.onset(ei) + manualEvents.duration(ei) ...
        );
    if any(overlap)
        error = true;
        message = ['Cancelled: cannot copy the set of sleep windows of type ''' thisEvents.type{1} ''' to the ''manual'' set because at least one pair of those windows overlap.'];
        return
    end
end

end