function [ACT, err, msg] = cic_checkDataset(ACT)
% ---------------------------------------------------------
% Write history
ACT.history = char(ACT.history, '% ---------------------------------------------------------');
ACT.history = char(ACT.history, '% Check if ACT structure contains all required fields');
ACT.history = char(ACT.history, '[ACT, err, msg] = cic_checkDataset(ACT);');
ACT.history = char(ACT.history, 'if err; error(msg); end');
% ---------------------------------------------------------
% Cell array of fieldnames that must exist in the ACT structure
mainFields = {
    'filepath', ...
    'filename', ...
    'info', ...
    'pnts', ...
    'srate', ...
    'xmin', ...
    'xmax', ...
    'startdate', ...
    'enddate', ...
    'times', ...
    'timezone', ...
    'epoch', ...
    'data', ...
    'metric', ...
    'analysis', ...
    'stats', ...
    'saved'
};
% ---------------------------------------------------------
% Expect all is well
err = true;
msg = '';
% ---------------------------------------------------------
% Check if all main fields exist
if sum(isfield(ACT, mainFields)) ~= length(mainFields)
    err = false; msg = [msg '\nFile does not contain all required data fields'];
end

end % EOF
